services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    image: ${DOCKER_HUB_USERNAME}/campuslink-backend:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://root:mysecretpassword@db:5432/mydb?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_PASSWORD=${JWT_PASSWORD}
      - FRONTEND_URL=http://${INSTANCE_IP}:3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: ${DOCKER_HUB_USERNAME}/campuslink-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata:
